//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estadistica
    {
        public int IdUsuario { get; set; }
        public int IdNivelIngles { get; set; }
        public Nullable<int> RespuestasCorrectas { get; set; }
        public Nullable<int> ErroresTotales { get; set; }
        public Nullable<int> NumeroTotalPreguntas { get; set; }
    
        public virtual NivelIngle NivelIngle { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
